"""empty message

Revision ID: 2364edf65a5a
Revises: be2a5f6cbb9f
Create Date: 2022-02-03 00:36:21.323008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2364edf65a5a'
down_revision = 'be2a5f6cbb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###
