"""empty message

Revision ID: 2cd764e7f485
Revises: ac206fbe348e
Create Date: 2022-02-15 00:35:30.032397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd764e7f485'
down_revision = 'ac206fbe348e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_parcel', sa.Column('report_date', sa.DateTime(), nullable=False))
    op.add_column('return_parcel', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_parcel', 'updated_date')
    op.drop_column('return_parcel', 'report_date')
    # ### end Alembic commands ###
