"""empty message

Revision ID: b65579df445f
Revises: 2cd764e7f485
Create Date: 2022-02-19 15:09:05.292207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b65579df445f'
down_revision = '2cd764e7f485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('due_charge', sa.String(length=100), nullable=True))
    op.drop_column('merchant', 'due_chare')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('due_chare', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('merchant', 'due_charge')
    # ### end Alembic commands ###
