"""empty message

Revision ID: d92206a21e48
Revises: 2364edf65a5a
Create Date: 2022-02-03 21:31:47.498219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd92206a21e48'
down_revision = '2364edf65a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'profile_image')
    op.add_column('users', sa.Column('profile_image', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.add_column('merchant', sa.Column('profile_image', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
